trigers:
- branches:
    include:
      #- main
      - kishan_testing
pool:
  name: Default
script:
- script: echo "Running training pipeline"
  displayName: 'Run Training Script'
- script: bash hello.sh
  displayName: 'Run Hello Script'
- script: echo "Training completed successfully!"
  displayName: 'Completion Message'
